### ISSUE TITLE
Migration guide/ adapted README for 'css' prop removal

### ISSUE THREAD

**Issue by Eliasvdb** [rebassjs/grid#180]
Our project build just broke because the css property is no longer supported as of v6.0.0 recently released (commit 2667fa6 to be specific).

The README still mentions 'css (string|object)' under properties, can this please be updated to reflect the current supported properties and would it be possible to provide a migration guide for how to keep using the css property?

I am trying to fix our code now but it is not clear to me what one should do to keep using the css property as before, which dependencies are needed, which configuration changes etc...

Thanks!

**Comment by jxnblk** [comment]
Thanks, the v6 beta releases included the `css` prop because styled-components hadn't released support for it when I started migrating this library to the rebassjs org. To enable support for the prop, you'll need to use the babel plugin from either styled-components or emotion. This is an example of a userland feature that went upstream, so hopefully it doesn't break your build once you have the babel plugin set up. From the Rebass docs: https://rebassjs.org/props#css-prop (scroll down, link is broken) and docs from styled-components: https://www.styled-components.com/docs/api#css-prop

**Comment by jxnblk** [comment]
The `css` prop is back in https://rebassjs.org/reflexbox without the need for Babel configuration
